### PR TITLE
Make tests work?

### PR DESCRIPTION
**Pull request by benjaoming**
Tested the tests and they seem to run now, I think this solves what @dlobo reported

### CODE REVIEW

**Comment by benjaoming** [comment]
@MCGallaspy conflicts now to resolve, could you have a look at merging this?

**Comment by benjaoming** [comment]
@dlobo just seeing your comments on hipchat, this PR is intended to solve your test case issues, not sure if you noticed it.

**Comment by MCGallaspy** [comment]
I get the following error: 

```
(kolibri) D:\kolibri>tox -e py2.7
GLOB sdist-make: D:\kolibri\setup.py
py2.7 inst-nodeps: D:\kolibri\.tox\dist\kolibri-0.0.1.zip
py2.7 installed: Error [Error 2] The system cannot find the file specified while executing command git config remote.origin.url,cannot determine version of editable source in d:\kolibri (git command not found in path),You are using pip version 7.1.2, however version 8.0.2 is available.,You should consider upgrading via the 'python -m pip install --upgrade pip' command.,colorama==0.3.6,colorlog==2.6.0,coverage==4.0.3,Django==1.9.1,django-mptt==0.8.0,docopt==0.6.2,-e kolibri==0.0.1,py==1.4.31,pytest==2.8.7,pytest-cov==2.2.1,pytest-django==2.9.1,wheel==0.24.0
py2.7 runtests: PYTHONHASHSEED='521'
py2.7 runtests: commands[0] | py.test --cov=kolibri --color=no
Test KOLIBRI_HOME exists: D:\kolibri/kolibrihome_test
Delete and continue? INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\main.py", line 86, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\config.py", line 830, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\kolibri\conftest.py", line 38, in pytest_configure
INTERNALERROR>     yn = compat.input("Delete and continue? ")
INTERNALERROR>   File "d:\kolibri\.tox\py2.7\lib\site-packages\_pytest\capture.py", line 433, in read
INTERNALERROR>     raise IOError("reading from stdin while output is captured")
INTERNALERROR> IOError: reading from stdin while output is captured
ERROR: InvocationError: 'D:\\kolibri\\.tox\\py2.7\\Scripts\\py.test.EXE --cov=kolibri --color=no'
___________________________________ summary ___________________________________
ERROR:   py2.7: commands failed
```

**Comment by MCGallaspy** [comment]
Not present on my branch, only after merging this.

**Comment by benjaoming** [comment]
Oh right, this seems to be an untested edge case. Since you have it all ready in your failing local env, could you find a way to resolve it? It's just meant to be a helpful prompt for anyone who tries to overwrite a non-default KOLIBRI_HOME

**Comment by MCGallaspy** [comment]
Okay, can you open an issue on the Kolibri repo for this? I'm stopping Kolibri dev for the time being to focus on KA Lite, so I don't want to forget about this.

**Pull request closed without merging**
